#!/bin/bash

# Instalar dependencias del sistema necesarias para Playwright
apt-get update
apt-get install -y --no-install-recommends \
	wget \
	gnupg \
	libasound2t64 \
	libatk-bridge2.0-0 \
	libatk1.0-0 \
	libatspi2.0-0 \
	libdbus-1-3 \
	libgbm1 \
	libnspr4 \
	libnss3 \
	libxcomposite1 \
	libxdamage1 \
	libxfixes3 \
	libxkbcommon0 \
	libxrandr2 \
	libxss1 \
	libxtst6
apt-get clean
rm -rf /var/lib/apt/lists/*

# Instalar Playwright browsers después de que se instalen las dependencias de Python
python -m playwright install chromium
