name: empresa-extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - google-generativeai>=0.3.0
    - pandas>=1.5.0
    - beautifulsoup4>=4.11.0
    - lxml>=4.9.0
    - openpyxl>=3.0.0
    - playwright>=1.30.0
    - aiohttp>=3.8.0
    - requests>=2.28.0
    - urllib3>=1.26.0
    - jupyter>=1.0.0
    - ipywidgets>=8.0.0
    - matplotlib>=3.5.0
    - seaborn>=0.11.0
    - plotly>=5.0.0
    - regex>=2022.0.0
    - python-dotenv>=0.19.0
