name: empresa-extraction-2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pip
  - pip:
    # IA y Análisis
    - google-generativeai>=0.8.0
    # Datos y Excel
    - pandas>=2.0.0
    - openpyxl>=3.1.0
    # Web scraping
    - beautifulsoup4>=4.12.0
    - lxml>=4.9.0
    - playwright>=1.40.0
    # HTTP y red
    - aiohttp>=3.9.0
    - requests>=2.31.0
    - urllib3>=2.0.0
    # Utilidades
    - regex>=2023.12.0
    - python-dotenv>=1.0.0
    # Jupyter y visualización
    - jupyter>=1.0.0
    - ipywidgets>=8.1.0
    - matplotlib>=3.8.0
    - seaborn>=0.13.0
    - plotly>=5.17.0
